### ISSUE TITLE
Clarify JSX when using list.map

### ISSUE THREAD

**Issue by konaraddi** [the-road-to-learn-react/the-road-to-learn-react#100]
Regarding this section: https://github.com/the-road-to-learn-react/the-road-to-learn-react/blob/master/manuscript/chapter1.md#complex-javascript-in-jsx

The following returns an Array of HTML elements in JSX.
```javascript
{list.map(function(item) {
          return <div>{item.title}</div>;
        })}
```
I think it should be clarified/mentioned that this returns an Array of HTML elements which React automatically loops through and renders each element in the array. 

In other words, the reader should know that React can work with this:
```javascript
{
[
<h1>H1 header</h1>,
<h2>H2 header</h2>,
<h3>H3 header</h3>
]
}
```

**Comment by rwieruch** [comment]
Hey @konaraddio Thanks for mentioning it! I had this Aha-moment in the early stages of learning React as well. It might be good to leave it out the book to let people come across this at some point too. I remember that it was a great learning for myself :) Do you think that's a valid thought?
