### ISSUE TITLE
Warning in Test in Chapter 4

### ISSUE THREAD

**Issue by HansWurst90** [the-road-to-learn-react/the-road-to-learn-react#101]
[Here](https://gist.github.com/HansWurst90/fe62ba49186deb77ada7ee84865a762a) is my code.

I am getting a warning when testing my App at the beginning of the Testing chapter:
```
 PASS  src/App.test.js
  ✓ renders without crashing (45ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 totalTime:        1.008s
Ran all test suites related to changed files.
Watch Usage
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
  console.error node_modules/fbjs/lib/warning.js:33
    Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

    Please check the code for the App component.
```
For some reason is says I am setting the state before the component is mounted. I found the ```setState()``` that triggered is the warning is the one from ```fetchSearchTopStories()```
```
  fetchSearchTopStories(searchTerm, page = 0) {
    fetch(`${PATH_BASE}${PATH_SEARCH}?${PARAM_SEARCH}${searchTerm}&${PARAM_PAGE}${page}&${PARAM_HPP}${DEFAULT_HPP}`)
      .then(response => response.json())
      .then(result => this.setSearchTopStories(result))
      .catch(e => this.setState({error: e}));
  }
```
although it is specifically called in ```componentDidMount()```
```
  componentDidMount() {
    const {searchTerm} = this.state;
    this.setState({searchKey: searchTerm});
    this.fetchSearchTopStories(searchTerm);
  }
```
when I comment ```fetchSearchTopStories()``` in ```componentDidMount()``` the warning does not appear.
It's "only" a warning, not an error but I was just wondering if I did something wrong and if I'm the only one with that warning. I did add the isomorphic-fetch but I don't think it is connected to that anyways.

**Comment by scotteza** [comment]
I figured out where this one comes from. Not sure **why** it is happening, but I can see the source.

When you use create-react-app to initialize the first version of the application, App.test.js looks like this:

```import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<App />, div);
  ReactDOM.unmountComponentAtNode(div);
});
```

If you download the source code for chapter four, you will notice that App.test.js doesn't contain this line:
`ReactDOM.unmountComponentAtNode(div);`

If you remove this line, the error goes away. I sadly don't know enough about React yet to say why this happens though.

**Comment by rwieruch** [comment]
Oh that's new! I will check this when I come to the next edition of the book. Thanks for finding out about it. I have to checkout ReactDOM.unmountComponentAtNode(div); and why it's there :)

**Comment by bpod** [comment]
@rwieruch @scotteza This is most likely due to the async nature of `fetch`. Seems like the test is trying to unmount the app when the lifecycle has not completed yet. 

Since `unmountComponentAtNode()` returns a `bool`, declaring a flag to check if the fetch has completed yet (before un-mounting), fixes this locally for me. This could probably be done cleaner (maybe async/await in Jest?? https://facebook.github.io/jest/docs/en/tutorial-async.html)... but Let me know what you think.

**App.js**
```
  componentDidMount() {
    const { searchTerm } = this.state;
    this.setState({
      searchKey: searchTerm
    });

    // ADD THIS
    this.didFetch = this.fetchSearchTopStories(searchTerm);
  }
```

**App.test.js**
```
it("renders without crashing", () => {
  const div = document.createElement("div");
  ReactDOM.render(<App />, div);
   
  // ADD THIS
  App.didFetch ? ReactDOM.unmountComponentAtNode(div) : null;
});
```

**Comment by rwieruch** [comment]
The native fetch request is not abortable, but it's in discussion for an official implementation.

See how you can use axios instead of fetch to cancel the request on componentWillUnmount: 
* version 1: https://github.com/the-road-to-learn-react/hackernews-client/pull/5
* version 2: https://github.com/the-road-to-learn-react/hackernews-client/pull/6

**Comment by rwieruch** [comment]
Should be fixed in Edition 5 (https://github.com/the-road-to-learn-react/the-road-to-learn-react/pull/105), but I keep this issue open for now for people running into it with an old edition.

**Comment by lex111** [comment]
@rwieruch why open again?
