### ISSUE TITLE
npm install vs npm install --save

### ISSUE THREAD

**Issue by sanspace** [the-road-to-learn-react/the-road-to-learn-react#103]
In Chapter 1, Under Node and NPM Intro:

> Command Line
> npm install react
> The installed package will automatically appear in a folder called node_modules/ and will be listed
> in the package.json file next to your other dependencies

https://github.com/the-road-to-learn-react/the-road-to-learn-react/blob/master/manuscript/chapter1.md#node-and-npm-1 

As per npm docs:

> To add an entry to your package.json's dependencies:
> 
> npm install <package_name> --save

I think the explanation `will be listed in the package.json file next to your other dependencies` is misleading as one will have to use `--save` option to do that.

**Comment by rwieruch** [comment]
Hey @sanspace thank you for pointing this out. Since npm 5.0 you don't need to use the --save flag anymore. It's the default.

**Comment by sanspace** [comment]
Good to know! I was sure I'll get to learn something out of it. :smile:
