### ISSUE TITLE
Introduce Yarn 

### ISSUE THREAD

**Issue by sujinleeme** [the-road-to-learn-react/the-road-to-learn-react#106]
As you know, Create-React-Native-App does not currently work well with NPM v5, due to bugs in NPM. While there should be no issues with NPM v3 or v4, why don't you suggest using `yarn` alternatively to be safe?

Related Chapter : https://github.com/the-road-to-learn-react/the-road-to-learn-react/blob/master/manuscript/chapter1.md#node-and-npm

**Comment by rwieruch** [comment]
Good Point. Maybe only mentioning it in one paragraph at the end of the **npm & node** chapter? I wouldn't want to introduce too much tooling in the beginning of the book. It should give you all the essentials for React, but not too much more of it.

**Comment by romerorocha** [comment]
I'm on it, if it is ok.

Should I talk about React Native (Expo/CRNA) issues with npm itself (and suggest yarn), or just give a small description of Yarn and mention it as a well adopted alternative to npm? 

Asking it because React Native is not the main subject in the book. Still a good point to mention and a relevant issue.

**Comment by romerorocha** [comment]
Asking it because React Native is not the main subject in the book. Still a good point to mention and a relevant issue.

**Comment by rwieruch** [comment]
I think the latter is best, because the problems with npm and React Native may go away in the future. We shouldn't confuse readers too much with those details. I think mentioning yarn as alternative is okay here :)

**Comment by rwieruch** [comment]
Introduced in https://github.com/the-road-to-learn-react/the-road-to-learn-react/pull/146
