### ISSUE TITLE
Splitting src/App.js

### ISSUE THREAD

**Issue by doradora-by-doris** [the-road-to-learn-react/the-road-to-learn-react#112]
I just finished chapter 6 and as you recommended in chapter 4, I'm going to split up the components into multiple modules. Following one of the possible module structures you proposed in chapter 4, I split `src/App.js` and extract constants from App component to `src/constants/index.js` as below:

```
src/
  index.js
  index.css
  constants/
    index.js
  components/
    App/
      index.js
      index.css
    ...
```

and import the constants into `src/components/App/index.js`:

``` jsx
import {
  DEFAULT_QUERY,
  DEFAULT_HPP,
  PATH_BASE,
  PATH_SEARCH,
  PARAM_SEARCH,
  PARAM_PAGE,
  PARAM_HPP,
} from '../constants';
```

but the relative path of `src/constants/index.js` is `'../../constants'`, not `'../constants'`, I would think.

**Comment by rwieruch** [comment]
Yes you are right! 💯Is it different in the book? If it is, would you want to open a Pull Request for it? :) Thanks for noticing this mistake and opening up this issue 👍
