### ISSUE TITLE
React 16.3: Add/Remove Lifecycle Methods to "Lifecycle Methods Chapter"

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-learn-react/the-road-to-learn-react#115]
The book has a lifecycle methods chapter which explains in a short paragraph each lifecycle method. Since [React 16.3 got released](https://reactjs.org/blog/2018/03/29/react-v-16-3.html), there are 2 new lifecycle methods:

* [getDerivedStateFromProps(nextProps, prevState)](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops)
* [getSnapshotBeforeUpdate(prevProps, prevState)](https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate)

It would be great to add those with a short explanation to the chapter next to the other lifecycle methods in the listing. On the other side, there are three lifecycle methods that got deprecated and can be removed from the book:

* componentWillMount
* componentWillReceiveProps
* componentWillUpdate

Is there anyone who wants to contribute to the book by opening a PR for this issue? :-)

Heads up for @azat-io @FrankFlow @GuillaumeUnice @JimmyLv @miseeger @romerorocha @sujinleeme as well!

**Comment by rwieruch** [comment]
Someone able to help out with this issue? Maybe it's a good topic for learning about the new lifecycle methods :)

**Comment by romerorocha** [comment]
Sure, I'm on it! :)

**Comment by rwieruch** [comment]
Fixed by @romerorocha in https://github.com/the-road-to-learn-react/the-road-to-learn-react/pull/143
