### ISSUE TITLE
Why the recommendation "UI Components: You shouldn't make the mistake to introduce too early a UI component library in your project."?

### ISSUE THREAD

**Issue by yxchng** [the-road-to-learn-react/the-road-to-learn-react#117]
Can I know what is the rationale for this recommendation? In my opinion, a UI library will make prototyping much faster.

**Comment by rwieruch** [comment]
You are right. But this recommendation stays in the context of learning React. So I believe it's good in the beginning, when learning about React, to implement Dialogs, Dropdowns or Tables on your own for the sake of learning about React. Once you got these things up and running, you can start to introduce a library such as Semantic UI for it. Does it make sense for you? 

However, you are right, if you are a seasoned developer using React, using a UI library for prototyping makes much sense! 👍
