### ISSUE TITLE
Page 21 broken code snippet?

### ISSUE THREAD

**Issue by lasernite** [the-road-to-learn-react/the-road-to-learn-react#12]
```
function isSearched(query) {
    return function(item) {
        return !query || item.title.toLowerCase().indexOf(query.toLowerCase()) !== -\
1;
        }
}
```

"Syntax error: Unterminated regular expression (26:81)"

**Comment by lasernite** [comment]
Dyou mean `return !query || item.title.toLowerCase().indexOf(query.toLowerCase()) !== -/1/;` ?

**Comment by rwieruch** [comment]
Argh, the line break is a bit confusing here. I have to fix that. It's:

`return !query || item.title.toLowerCase().indexOf(query.toLowerCase()) !== -1;`

**Comment by lasernite** [comment]
Thanks! Probably just removing the the "\\\" is the most easy to understand. Or you could put the symbol in another color?

**Comment by tyleri** [comment]
Even though I understood the intention, I also felt that the backslashes for broken lines was a little confusing. Maybe instead, you could break up the line in a way that's also syntactically correct in Javascript? For example,

```javascript
function isSearched(query) {
    return function(item) {
        return !query
               || item.title.toLowerCase().indexOf(query.toLowerCase()) !== -1;
        }
}
```

I think using this style is easier to read and understand.

**Comment by rwieruch** [comment]
https://github.com/rwieruch/the-road-to-learn-react/commit/04d47b2d28e9c50fe104d421e72959cb94e13012
