### ISSUE TITLE
Changes in ref API

### ISSUE THREAD

**Issue by matchatype** [the-road-to-learn-react/the-road-to-learn-react#122]
As of React 16.3, there have been changes in the [createref-api](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#createref-api). You can set your refs in the subclass constructor function, however, since _create-react-app_ supports class fields you can also simply take advantage of that:
```js
class Search extends React.Component {
  textInput = React.createRef()

  componentDidMount() {
    this.textInput.current.focus()
  }

  render() {
    const { onSearchChange, onSearchSubmit, searchTerm, children } = this.props

    return (
      <form onSubmit={onSearchSubmit}>
        {children}
        <input
          type="text"
          onChange={onSearchChange}
          value={searchTerm}
          ref={this.textInput}
        />
        <button type="submit">{children}</button>
      </form>
    )
  }
}

export { Search }
```
If you run your tests now, those related to the `<Search />` component should fail, and the reason is that the test renderer is not coupled to ReactDOM, and doesn't know anything about what refs are supposed to look like. So you should mock refs for test renderer, as [documented](https://reactjs.org/docs/test-renderer.html#ideas). In the `describe block` I added the following:

```js
const createNodeMock = element => {
  if (element.type === 'input') {
    return {
      focus() {},
    }
  }
  return null
}
```
Don't forget to pass the options object to the renderer inside your test:
```js
it('should render Search component correctly', () => {
  const options = { createNodeMock }

  const component = renderer.create(<Search />, options)
  let tree = component.toJSON()

  expect(tree).toMatchSnapshot()
})
```

**Comment by rwieruch** [comment]
Duplicate
