### ISSUE TITLE
Filter functionality, p. 57 hard copy

### ISSUE THREAD

**Issue by 76784** [the-road-to-learn-react/the-road-to-learn-react#129]
Enjoying your fine book (I purchased the hard copy, but I see you have the material here as well). I have a question. In the chapter "Basics in React", when you discuss filtering, there is some code that is abbreviated using "...":

[Basics in React](https://github.com/the-road-to-learn-react/the-road-to-learn-react/blob/master/manuscript/chapter2.md)

~~~
  render() {
    return (
      <div className="App">
        <form>
          <input
            type="text"
            onChange={this.onSearchChange}
          />
        </form>
# leanpub-start-insert
        {this.state.list.filter(isSearched(this.state.searchTerm)).map(item =>
# leanpub-end-insert
          ...
        )}
      </div>
    );
  }
~~~
 
I have gone over the material several times, but I don't know what would actually go in to that "..." placeholder."The search functionality should work now. Try it yourself in the browser." - this doesn't seem to be the case. Running the code without replacing "..." results in an error, I'm afraid.

Also, I don't understand what # leanpub-start-insert and # leanpub-end-insert mean.

Any help would be appreciated. Thank you.

**Comment by rwieruch** [comment]
Hello @76784 

In this GitHub repository you find only the raw manuscript which is used to generate all different formats (e.g. PDF, EPUB, MOBI). The leanpub-start-insert are only used to generate those formats and to highlight the lines. In the book/ebook, this line should be highlighted then.

For the ... content you can go back to the "Internal Component State" chapter. There this content was shown the last time, but never touched afterward, and therefore I tend to use those placeholders for them. After all, it should be something like this:

```
 {this.state.list.filter(isSearched(this.state.searchTerm)).map(item =>
    <div key={item.objectID}>
      <span>
              <a href={item.url}>{item.title}</a>
            </span>
            <span>{item.author}</span>
            <span>{item.num_comments}</span>
            <span>{item.points}</span>
          </div>
        )}
      </div>
```

I hope this helps you :)

**Comment by 76784** [comment]
Got it - thanks for the reply. (And sorry for my slow response.)

**Comment by rwieruch** [comment]
No worries :) Glad that it worked!
