### ISSUE TITLE
Basics in React -> Interactions in Components -> ES6 Sugar suggestion

### ISSUE THREAD

**Issue by robertf224** [the-road-to-learn-react/the-road-to-learn-react#13]
Since we're doing ES6 stuff here anyway, might also want to use .includes() over .indexOf() !== -1

(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

**Comment by rwieruch** [comment]
Great find! 👍

**Comment by rwieruch** [comment]
https://github.com/rwieruch/the-road-to-learn-react/commit/04d47b2d28e9c50fe104d421e72959cb94e13012
