### ISSUE TITLE
Using JavaScript ES6 to define functions instead of bind (Suggestion)

### ISSUE THREAD

**Issue by tyleri** [the-road-to-learn-react/the-road-to-learn-react#14]
This is kind of a follow-up to #9, but I'd like to suggest using ES6 arrow functions to define the functions in App. For example, the following example from the book:

```javascript
class App extends Component {

  constructor(props) {
    ...
    this.onSearchSubmit = this.onSearchSubmit.bind(this);
  }

  onSearchSubmit() {
    const { query } = this.state;
    this.fetchSearchTopstories(query);
  }

  ...
}
```

could also be expressed as:

```javascript
class App extends Component {

  constructor(props) {
    ... // this.onSearchSubmit is not defined here
  }

  onSearchSubmit = () => {
    const { query } = this.state;
    this.fetchSearchTopstories(query);
  }

  ...
}
```

Even though the official React tutorials use bind, since using ES6 is encouraged, I think it'd be a good idea to incorporate this usage. By the way, I got this idea from the [MDN page about arrow functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions#No_binding_of_this), which is linked in Chapter 1 on page 11.

**Comment by rwieruch** [comment]
@tyleri thanks for the suggestion and sorry for my late reply on this! I think I will mention it, but I would stick to the official documented way for now.

**Comment by heticeric** [comment]
Completely agree with @tyleri. 
Why just not using arrow function that use lexical scope for this !

```
    render()
    {
        // No need to bind arrow functions
        return (<div onClick={ ()=>{ this.clicked( 'what' ) } }>I'm statefull</div> );
    }
```

I don't personally see any reason to stick with FB, since ES6.

**Comment by doureyd** [comment]
I think that Facebook will probably move to the ES6 arrow functions in the future. You can find more information about the different Binding Patterns in [this article](https://medium.com/@housecor/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56).

**Comment by rwieruch** [comment]
Thank you very much @daynox ! I will consider it for the next edition 👍

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/69b2a4696435d4114b80616ec17b9e8aa7cbc15b
