### ISSUE TITLE
url parameter p101 hard copy

### ISSUE THREAD

**Issue by 76784** [the-road-to-learn-react/the-road-to-learn-react#140]
I'm not sure which edition of the hard copy of the book I have, but it does have, in the change log, "17.February 2018", so I think it might be the latest.

On page 101 of this hard copy, there is the following under Code Playground:

const url = `${PATH_BASE}${PATH_SEARCH}?${PARAM_SEARCH}${searchTerm}&${PARAM_PAGE}`;

I gather that because this is listed under Code Playground, it is not meant to go into App.js (the file I am building throughout the book). 

Nevertheless, it is confusing, because that const is in App.js. And when you change this:

const url = `${PATH_BASE}${PATH_SEARCH}?${PARAM_SEARCH}${DEFAULT_QUERY}`;

...to this:
const url = `${PATH_BASE}${PATH_SEARCH}?${PARAM_SEARCH}${searchTerm}&${PARAM_PAGE}`;

...you get an error ('searchTerm' is not defined  no-undef).

And nowhere in the text does it say that one should have this const:

const url = `${PATH_BASE}${PATH_SEARCH}?${PARAM_SEARCH}${DEFAULT_QUERY}&${PARAM_PAGE}`;

...which I believe (correct me if I'm wrong) is what one needs to have in that const.

I do understand that fetchSearchTopStories needs to look like this:

  fetchSearchTopStories(searchTerm, page = 0) {
    fetch(`${PATH_BASE}${PATH_SEARCH}?${PARAM_SEARCH}${searchTerm}&${PARAM_PAGE}${page}`)
      .then(response => response.json())
      .then(result =>  this.setSearchTopStories(result))
      .catch(error => error);
  }

**Comment by rwieruch** [comment]
You are totally right. It should say `${PATH_BASE}${PATH_SEARCH}?${PARAM_SEARCH}${DEFAULT_QUERY}&${PARAM_PAGE}` in the Code Playground example, shouldn't it? 

https://github.com/the-road-to-learn-react/the-road-to-learn-react/commit/91664bc1fbc4d82376ec5470c03bc073e95d3b62

Good find! 👍
