### ISSUE TITLE
Confusion about the spread operator (suggestion)

### ISSUE THREAD

**Issue by tyleri** [the-road-to-learn-react/the-road-to-learn-react#16]
In the function setSearchTopstories, the following code is used to update `state.results` with a new list of hits for the searchKey:

```javascript
this.setState({
  results: { ...this.state.results, [searchKey]: { hits: updatedHits, page } }
});
```

I was slightly confused about this usage of the spread operator, because the [linked MDN page](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator#Only_for_iterables) says "Note that the spread operator can be applied only to iterable objects." After looking it up myself, I found out that the spread operator for objects is actually not officially in ECMAScript yet, but React has already incorporated it, so it's a React-specific feature for now (not ES6). It might be a good idea to add a note about this in the text for others who get confused about this.

**Comment by rwieruch** [comment]
Yes, seems like I forgot to mention it properly! Will improve all the issues today 👍 Thank you so much!

**Comment by rwieruch** [comment]
https://github.com/rwieruch/the-road-to-learn-react/commit/a7eaf820916684e942d4dba0a4baf71124ac0b64

**Comment by tyleri** [comment]
This looks good! I think you can close this issue 🙂
