### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by tsvecak** [the-road-to-learn-react/the-road-to-learn-react#180]
Opening this so that people can help you out with typos :)

I have just recently started reading your book and found a typo on the FAQ pages under What's your motivation behind the book? "Recently I'v found myself" should be "I've"

Cheers!

**Comment by rwieruch** [comment]
You can open a Pull Request instead :) Then you can actively contribute to the book! When I merge the Pull Request then, we can close this issue.

Thanks for noticing this 👍 💯 Hope you enjoy the book :)

**Comment by tsvecak** [comment]
Just added pull request there.

Cool way to get people involved- seriously good work!

Book is amazing - great for beginners but also great for the more advanced developers!

**Comment by rwieruch** [comment]
Thank you @tsvecak Hope you enjoy the rest of the book :)

Ref.: https://github.com/the-road-to-learn-react/the-road-to-learn-react/pull/182
