### ISSUE TITLE
Translate to Vietnamese

### ISSUE THREAD

**Issue by petixiuxx** [the-road-to-learn-react/the-road-to-learn-react#185]
Hi Robin, I'm glad to help you translate the book to Vietnamese.
However, I'm confused about how to do it. Can you give me a hint ? ^^

**Comment by rwieruch** [comment]
Hey @petixiuxx Happy to have you on board. You have access to https://github.com/the-road-to-learn-react/the-road-to-learn-react-vietnamese From there you can start to translate the manuscript and README.md :) Once you finished, I will connect it to Leanpub to generate the ebook from it. Let's continue this chat via E-Mail: hello@rwieruch.com :)
