### ISSUE TITLE
Table component test failing in "Snapshot Tests with Jest" section

### ISSUE THREAD

**Issue by zolbayars** [the-road-to-learn-react/the-road-to-learn-react#195]
Hi, 
On page 131 of the pdf book (Chapter 4, "Snapshot Tests with Jest" section). There's a following test case: 
```
describe('Table', () => {

  const props = {
    list:[
      { title: '1', author: '1', num_comments: 1, points: 2, objectID: 'y' },
      { title: '2', author: '2', num_comments: 1, points: 2, objectID: 'z' },
    ],
  };
  
  it('renders without crashing', () => {
    const div = document.createElement('div');
    ReactDOM.render(<Table { ...props } />, div); 
    ReactDOM.unmountComponentAtNode(div);
  });

  test('has a valid snapshot', () => {
    const component = renderer.create(
      <Table { ...props } />
    );
    const tree = component.toJSON(); 
    expect(tree).toMatchSnapshot(); 
  });

});
```
It's failing the test with following error: 
![image](https://user-images.githubusercontent.com/3589907/54172690-e437a000-44b9-11e9-92b8-f2ebd47b520b.png)

I think the line `<Table { ...props } />` should be `<Table result={ props.list } />`. When I [change it like that](https://github.com/zolbayars/hackernews/blob/master/src/App.test.js), it passes. 

Node version: v8.11.4
OS: Windows 10

**Comment by rwieruch** [comment]
I think it's because your Table component expects a result object whereas the Table from the book expects a list array.
