### ISSUE TITLE
More concise still?

### ISSUE THREAD

**Issue by lasernite** [the-road-to-learn-react/the-road-to-learn-react#2]
Line 332 of Chapter one, "{ list.map((item) =>", the docs referenced at the bottom of the page suggest you can even just do "{ list.map(item =>"? Any reason this wouldn't be preferred? 

Thanks for the resource, awesome so far!

**Comment by rwieruch** [comment]
Good point! You can do that. People leave out the brackets in arrow functions when they have only one argument. It might be even a common code style in ES6 already.I might change that in the book. Thanks 👍

**Comment by lasernite** [comment]
Thanks!

Another note (not sure how much pedantry is actually useful), "built-in JavaScript functionalities like map can be used render a list of items" should be "built-in JavaScript functionalities like map can be used **to** render a list of items" on page 13

**Comment by rwieruch** [comment]
Yes. I will change it when you don't do it :) Thanks for the hint again! Please stay pedantic 👍

**Comment by rwieruch** [comment]
Ok, I changed it. Thanks again :)
