### ISSUE TITLE
Couldn't get preventDefault() to work

### ISSUE THREAD

**Issue by iamwithnail** [the-road-to-learn-react/the-road-to-learn-react#20]
Having gone through the book (as of the version available 21st December, as I was using a printed copy based on 884f31e) 

I tried a number of things to get the `event.preventDefault()` line in `onSearchSubmit` to work - I understand from [this answer on SO](http://stackoverflow.com/a/36319301/1293222) that it's because of the Native event/Synthetic event difference.  Fundamentally though, wherever I had it, it still reloaded the page on submit.  (Chrome & Firefox)

Ended up using [an external package wrapper for this](https://www.npmjs.com/package/react-prevent-default) to make it work (Works perfectly after a simple `npm install react-prevent-default`, but this feels like a workaround rather than a fix) - I wondered if there's a longer explanation/route to get that `preventDefault()` working as written, or if I've missed something on it? 

(This might be out of date, judging by the number of commits i've seen here, but worth flagging in any case, as it seems like a thing people might trip up on.)

**Comment by tyleri** [comment]
Can you copy and paste your code for onSearchSubmit? It seems to work fine for me, and I've been following the version of the PDF I downloaded on December 18th.

**Comment by rwieruch** [comment]
As a reference https://github.com/rwieruch/hackernews-client that might help.

**Comment by rwieruch** [comment]
Will close this now, because we didn't hear anything back.

**Comment by cwoz117** [comment]
I see this error on: 
 - Firefox Developer Edition 67.0b16 (64-bit)
 - Microsoft Edge 44.17763.1.0
 - Chrome Version 74.0.3729.131 (Official Build) (64-bit)

with versions running on Ubuntu18.04 WSL:
- nodejs version v8.10.0
- npm version 3.5.2
- react version 16.8.5-canary-297165f1e

The physical book I'm using has its last changelog as 10. January 2017, but this section in chapter 3 appears unchanged (hard to diff w/ a piece of paper)

The code previously requested is below, and I have tried it without the anon function as well.
```javascript
onSearchSubmit = (event) => {
  const {searchTerm} = this.state
  this.fetchSearchTopStories(searchTerm);
  event.preventDefault();
}
```
[EDIT]: The issue arose when the guide requested us to modify onSearchSubmit to take an argument (event) which led to 'the most common bug' for react developers.

The `render()` function in our component must be an anonymous function now that it takes a variable. 
i.e. now `onSubmit={}` requires more than a function definition, it needs to be encapsulated in an anonymous function lest it only execute at runtime.

```javascript
<Search value={searchTerm}
        onChange={this.onSearchChange}
        onSubmit={(event) => {this.onSearchSubmit(event)}}>search</Search>
```

It would be beneficial to remind new programmers at this stage to change this code, as the previous page in the physical book instructs them to rewrite `onSearchSubmit` in the `render()` function away from proper usage:

```javascript
<Search value={searchTerm}
        onChange={this.onSearchChange}
        onSubmit={this.onSearchSubmit}>search</Search> // This won't fly, but the book says to write it.
```
