### ISSUE TITLE
Would you mind to change the `bit.ly links` to direct links ?

### ISSUE THREAD

**Issue by snowman** [the-road-to-learn-react/the-road-to-learn-react#205]
In China, with the Great Firewall, people live in China can't access almost every foreign websites, please help

**Comment by snowman** [comment]
no way, Chinese is stupid that I can't help with. They have to help themselves instead of requiring we make some changes.

**Comment by rwieruch** [comment]
You can't say I don't care about Chinese people: https://github.com/the-road-to-learn-react/the-road-to-learn-react-chinese If I would use direct links, they would be too long for the print edition of the book. Hence I used bitly links. Didn't know that they weren't accessible in China. Sorry. But I cannot work more than 24hours a day for free, so sorry that I cannot answer every issue. I am working on 4 books that are accessible for free in multiple languages most of my free time...
