### ISSUE TITLE
Use .md extension for chapter files

### ISSUE THREAD

**Issue by bpesquet** [the-road-to-learn-react/the-road-to-learn-react#23]
You could use a `.md` extension for the chapter files instead of `.txt`. It's an (undocumented) feature of Leanpub and it greatly improves rendering on GitHub.

**Comment by rwieruch** [comment]
Thanks for the hint @bpesquet ! I will test it 👍

**Comment by bpesquet** [comment]
You're welcome! Good luck on your book, i'll keep an eye on it.
