### ISSUE TITLE
stuck with code  at nteraction with forms and events

### ISSUE THREAD

**Issue by gideondsouza** [the-road-to-learn-react/the-road-to-learn-react#31]
Hi,

I bought your book. Thanks very much for it.

I'd really like to suggest having a per chapter branch or tag of this hacker news app. So that, like me, if someone gets stuck somewhere they can review what the code should look like at the end of that chapter by fetching that branch or tag in the repo.

I looked online, stackoverflow and the final hacknews app and still can't figure what is wrong here. I'd really appreciate it if you could help me a bit, below is the code and if I click the Dismiss button it cribs saying this `Cannot read property 'onDismiss' of undefined`

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

const list = [
  {
    title: 'React',
    url: 'https://facebook.github.io/react/',
    author: 'Jordan Walke',
    num_comments: 3,
    points: 4,
    objectID: 0,
  },
  {
    title: 'Redux',
    url: 'https://github.com/reactjs/redux',
    author: 'Dan Abramov, Andrew Clark',
    num_comments: 2,
    points: 5,
    objectID: 1,
  },
];

class App extends Component {

  constructor(props)
  {
    super(props);
    this.state = {
      list,
    };

    this.onDismiss = this.onDismiss.bind(this); 
  }
  

  onDismiss(id)
  {
    function isNotId(item) { return item.objectID !== id;}
    const updatedList = this.state.list.filter(isNotId);
    this.setState({list: updatedList});
  }

  render() {
    return (
      <div className="App">
        { 
          list.map(function(item) {
          return (
            <div key={item.objectID}>
              <span>
                <a href={item.url}>{item.title}</a>
              </span>
              <span>{item.author}</span>
              <span>{item.num_comments}</span>
              <span>{item.points}</span>
            <span>
              <button type="button" onClick={()=>{this.onDismiss(item.objectID)}}>Dismiss</button>
            </span>
            </div>
          );
        })}
      </div>
    );
  }
}
export default App;

```

**Comment by rwieruch** [comment]
Hi @gideondsouza Can you try

`<button type="button" onClick={() => this.onDismiss(item.objectID)}>`

instead of

`<button type="button" onClick={()=>{this.onDismiss(item.objectID)}}>`

Great idea to have a per chapter branch/tag! I will do it.

**Comment by rwieruch** [comment]
@gideondsouza I added references for each chapter in the source code repository. https://github.com/rwieruch/hackernews-client

**Comment by gideondsouza** [comment]
Wow. Thank you son much. Dankeschön!!

**Comment by shabbir1993** [comment]
@gideondsouza did it work for you ? I've tried it but still stuck there... @rwieruch can you please look into it ?

**Comment by rwieruch** [comment]
@shabbir1993 can you share your code on GitHub or somewhere else? Otherwise you can find the Source of each chapter here: https://github.com/rwieruch/hackernews-client

**Comment by gideondsouza** [comment]
Yes @shabbir1993 eventually it did I don't remember what fixed it **or** if I just moved forward to the chapter. I think posting your code in a gist or directly here would be helpful.

**Comment by shabbir1993** [comment]
@rwieruch Well thanks , just figured it out, it's working now, I had to change `list.map(function(item){...})` to arrow function and it worked

**Comment by rwieruch** [comment]
That's good to know! I will revisit the chapters and see if I can change something around this issue. Thanks again for your help!
