### ISSUE TITLE
Use of default parameter for fetchSearchTopstories

### ISSUE THREAD

**Issue by dudko** [the-road-to-learn-react/the-road-to-learn-react#36]
Hello,

first of all, thank you for you book! It's clear, gets to the point without overwhelming details, perfect starting point to the React world.

As a feedback, I would suggest to use [default parameter](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Default_parameters) in function `fetchSearchTopstories` in chapter **Paginated Fetch**.  You can then omit the second argument in the following calls.

**Comment by rwieruch** [comment]
Hi @dudko Thanks for the recommendation. Glad that you like it. I would change this in the next edition of the book. Since it is a code chance, I would need to apply it to another course too. That's why it makes sense to bulk these changes in the next edition. Thanks again!

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/44726df5c5434e330322dccc8e6de8951a908e2a
