### ISSUE TITLE
Object spread operator is not explained on first use

### ISSUE THREAD

**Issue by taufiqkh** [the-road-to-learn-react/the-road-to-learn-react#4]
When using the array spread operator for the first time, its use is mentioned and a link provided to the ES6 array spread operator. When the **object** spread operator is used for the first time however (pages 52-53) it might be worth mentioning its use and a similar link provided to a definition. The use of the object spread was in the following example:
```js
results: { ...this.state.results, [query]: { hits: updatedHits, page } }
```
The page linked to for the array spread operator (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator) does mention object spread but it only appears as a brief mention and does not explain its use or syntax. Suggested link is [https://github.com/sebmarkbage/ecmascript-rest-spread] but I'm not familiar enough to know if it is the definitive one.

**Comment by rwieruch** [comment]
Good catch! I had this in my mind at some point, but forgot about it. I added a brief explanation now, but kept the reference to the official developer.mozilla documentation. I know the proposal page by sebmarkbage, but I am unsure if it stays updated. Thanks for making me aware of it 👍

**Comment by taufiqkh** [comment]
No worries, been a good read, thanks!
