### ISSUE TITLE
Hot Module Replacement instead of Hot Module Reloading

### ISSUE THREAD

**Issue by doureyd** [the-road-to-learn-react/the-road-to-learn-react#41]
Just a little mistake in [Chapter 1](https://github.com/rwieruch/the-road-to-learn-react/blob/master/manuscript/chapter1.md#hot-module-reloading), here is the [Webpack Documentation](https://webpack.js.org/concepts/hot-module-replacement/#components/sidebar/sidebar.jsx).
Nice job by the way! 👍

**Comment by rwieruch** [comment]
@daynox are you referring to the naming? Or did something about the usage change as well? Thanks for pointing me in the direction :)

**Comment by doureyd** [comment]
@rwieruch Only the naming :)

**Comment by rwieruch** [comment]
Okay. Goes in into the next edition! Thanks :)
