### ISSUE TITLE
SORTS[sortKey] is not a function

### ISSUE THREAD

**Issue by aledavila** [the-road-to-learn-react/the-road-to-learn-react#42]
I have the same code that you have written and when i run the tests it fails at TABLE yet my application works just fine and I don't get any errors in the console.

**Comment by rwieruch** [comment]
Might be related to https://github.com/rwieruch/the-road-to-learn-react/issues/24 

Thanks for pointing it out. I will address it in the next edition. If you have any hints how to fix it, I would welcome them :)
