### ISSUE TITLE
code line breaks with \ confuse people

### ISSUE THREAD

**Issue by luk3nukem** [the-road-to-learn-react/the-road-to-learn-react#43]
Excellent book, thanks very much for putting this together.  I'm working through it and on page 84/85 where you deal with the pagination / Hacker news API the book mentions the following code:

```
<div className="interactions">
    <Button onClick={() => this.fetchSearchTopstories( searchTerm, page + 1\ )}>
        More
    </Button>
</div>
```
I was getting an error here, I think due to the \ after the page variable is increased by 1.  I.e. should be:

``` 
<Button onClick={() => this.fetchSearchTopstories( searchTerm, page + 1 )}>
````

If I am indeed correct, I hope that helps someone.

**Comment by rwieruch** [comment]
Hi @lholdsworth 

Thanks for opening the issue. The `\` is automatically added in the book when there is a line break. Unfortunately people run into this issue and it comes to confusion. I will address this problem in the next edition and try to keep the code lines short.

Thanks again 👍

**Comment by simon-shuffle** [comment]
glsdjfgl;kjd

**Comment by simon-shuffle** [comment]
excellent

**Comment by AdamMarczyk** [comment]
test comment

**Comment by AdamMarczyk** [comment]
test comment

**Comment by AdamMarczyk** [comment]
dddddd

**Comment by lex111** [comment]
It seems to me that this can not be fixed without forcing limit of lines to break (for example, the line of code should not exceed 50-60 characters)

**Comment by mastas3** [comment]
Thanks

**Comment by c-ancia** [comment]
test exercise comment from this link:
https://www.robinwieruch.de/react-graphql-apollo-tutorial/

**Comment by c-ancia** [comment]
test exercise comment from this link :
https://www.robinwieruch.de/react-graphql-apollo-tutorial/

**Comment by c-ancia** [comment]
test exercise comment from this link :
https://www.robinwieruch.de/react-graphql-apollo-tutorial/

**Comment by c-ancia** [comment]
test exercise comment from this link :
https://www.robinwieruch.de/react-graphql-apollo-tutorial/

**Comment by ZeeEssDoubleU** [comment]
afdfd

**Comment by ZeeEssDoubleU** [comment]
This is a new comment

**Comment by ZeeEssDoubleU** [comment]
Thing

**Comment by RicardoBastos** [comment]
aa

**Comment by TechStacker** [comment]
Great help, thank you!

**Comment by Nguyen1217** [comment]
tut

**Comment by Nguyen1217** [comment]
uiy

**Comment by jonportelli** [comment]
comment

**Comment by kinglarce** [comment]
Thanks

**Comment by kinglarce** [comment]
Thanks

**Comment by kinglarce** [comment]
testing

**Comment by kinglarce** [comment]
test

**Comment by kinglarce** [comment]
test

**Comment by kinglarce** [comment]
last one

**Comment by kinglarce** [comment]
asdf

**Comment by kinglarce** [comment]
asdfadsf

**Comment by kinglarce** [comment]
adsfa

**Comment by kinglarce** [comment]
asdf

**Comment by kinglarce** [comment]
asdfasdf

**Comment by kinglarce** [comment]
asdf

**Comment by kinglarce** [comment]
aaaa

**Comment by kinglarce** [comment]
qwewqe

**Comment by kinglarce** [comment]
qwewq

**Comment by kinglarce** [comment]
qweqwe

**Comment by kinglarce** [comment]
dfgh

**Comment by kinglarce** [comment]
rtyuyrtu

**Comment by kinglarce** [comment]
cvbncv

**Comment by kinglarce** [comment]
ryturtyu

**Comment by kinglarce** [comment]
weqrwqer

**Comment by kinglarce** [comment]
the tid

**Comment by kinglarce** [comment]
happening

**Comment by kinglarce** [comment]
agaga

**Comment by kinglarce** [comment]
wertwet

**Comment by kinglarce** [comment]
retertre

**Comment by kinglarce** [comment]
rwetrewt

**Comment by kinglarce** [comment]
wqeqwe

**Comment by kinglarce** [comment]
fghjfhgj
