### ISSUE TITLE
Tests pass but display console log errors

### ISSUE THREAD

**Issue by Fenwick17** [the-road-to-learn-react/the-road-to-learn-react#53]
Test Suite, Tests and Snapshots all correctly pass but terminal shows multiple console log errors.  
`console.error node_modules/fbjs/lib/warning.js:36
    Warning: Failed prop type: The prop value is marked as required in Search, but its value is undefined.
        in Search (at App.test.js:26`

  `console.error node_modules/fbjs/lib/warning.js:36
    Warning: Failed prop type: The prop onChange is marked as required in Search, but its value is undefined.
        in Search (at App.test.js:26)`

  `console.error node_modules/fbjs/lib/warning.js:36
    Warning: Failed prop type: The prop onSubmit is marked as required in Search, but its value is undefined.
        in Search (at App.test.js:26)`

  `console.error node_modules/fbjs/lib/warning.js:36
    Warning: Failed prop type: The prop `onClick` is marked as required in Button, but its value is undefined.
        in Button (at App.test.js:42)`

  `console.error node_modules/fbjs/lib/warning.js:36
    Warning: Failed prop type: The prop onDismiss is marked as required in Table, but its value is undefined.
        in Table (at App.test.js:64)`  

All packages listed in the book have been installed.

**Comment by rwieruch** [comment]
@Fenwick17 can you answer me a couple of questions that I can jump into the problem?

Which chapter/page does it happen for you? 
Did the tests never ran before or did they fail after a while? 
Which node version do you have (command line: node -v)?
Do you have your GitHub repository somewhere accessible to check the code?

Thanks for your help!
Note: It's not related to the network requests, is it? This was already reported and will get fixed: https://github.com/rwieruch/the-road-to-learn-react/issues/24 & https://github.com/rwieruch/hackernews-client/issues/2

**Comment by Fenwick17** [comment]
https://github.com/Fenwick17/road-to-react-learning This is the repo for my progess which includes console log errors.  
The tests all pass correctly, console logs display after the test pass.  
Node - v8.1.2  
Yarn - 0.21.3  
NPM - 5.0.3

**Comment by rwieruch** [comment]
I see. Nothing to worry about @Fenwick17 You defined PropTypes for your components, such as:

```
Search.propTypes = {
  value: PropTypes.string.isRequired,
  onChange: PropTypes.func.isRequired,
  onSubmit: PropTypes.func.isRequired,
  children: PropTypes.node.isRequired,
}
```

 and don't pass these props in your tests to the component. For your tests you can make up props for your test cases, like you did for the Table component:

```
  const props = {
    list: [
      { title: '1', author: '1', num_comments: 1, points: 2, objectID: 'y' },
      { title: '2', author: '2', num_comments: 1, points: 2, objectID: 'z' },
    ],
  }
```

I should definitely update it since it shows up in the test log (which it didn't a few updates before). Sorry for this!

**Comment by Fenwick17** [comment]
@rwieruch All good, had a feeling it was nothing to worry about due to the tests themselves passing. Just a pit of terminal clutter.

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/3e7ca04351e6cca47eebbbfa69d4f53cd0f0bc90
