### ISSUE TITLE
Filtering list on onSearchChange behaves differently

### ISSUE THREAD

**Issue by vimalvnair** [the-road-to-learn-react/the-road-to-learn-react#55]
On Chapter "Basics in React" - "Interactions with Forms and Events"

I followed this chapter and created the search functionality, it works fine: When I type the search term, the list updates and when I hit backspace and remove the search terms,  also the list updates.

But when I made this modification: Instead of updating the `searchTerm` on `onSearchChange` and adding the filter for the list on `render` method, I did the filtering in the `onSearchChange` method and updated the list, similar to how it is done for `onDismiss`. 

```javascript
    onSearchChange(event) {
	let searchTerm = event.target.value;
	const updatedList = this.state.list.filter(isSearched(searchTerm));
	this.setState({ list: updatedList });
    }
```  
```html
  render() {
    return (
	    <div className="App">
	    <form>
	    <input type="text" onChange={this.onSearchChange} />
	    </form>
	    {this.state.list.map(item =>
        	 <div key={item.objectID}>
        	 <span>
.
.
```
the list is NOT updating when I hit backspace in the search box and remove the term one by one.

![diff](https://user-images.githubusercontent.com/1711390/28070734-981e89d2-666b-11e7-8ac0-41d189f34ef2.gif)

**Original, expected behavior:**

![orig](https://user-images.githubusercontent.com/1711390/28070797-ca6b5aa0-666b-11e7-891b-aa5a5c5d24e9.gif)
 

Any idea why this might be happening?

**Comment by vimalvnair** [comment]
I think I got the answer: `this.state.list` gets updated on the first search match. The unmatched item is removed from the list. This leaves only one item in the list. When we remove the search terms from the text box, it is searching on this new list with one item.

**Comment by rwieruch** [comment]
Yes. Your reasoning is right! 👍
