### ISSUE TITLE
On page 79, Changing search criteria in search textbox should not refresh search results. 

### ISSUE THREAD

**Issue by ajitgoel** [the-road-to-learn-react/the-road-to-learn-react#56]
On page 79, when one changes the search criteria in the search textbox, the code does not make a API call to get the data based on the new search criteria. It should be explained that the code will be refactored later on to do a complete search server-side(which will fix the above mentioned issue).

**Comment by rwieruch** [comment]
Thanks @ajitgoel Will go into the next edition!

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/59c747fab471a33c0bce14757e2e48a05bf59102
