### ISSUE TITLE
Page 87-89 - ES5 Object.assign()

### ISSUE THREAD

**Issue by fabriceci** [the-road-to-learn-react/the-road-to-learn-react#58]
> Let’s do it in JavaScript ES5. Object.assign() and ...
> That’s it in JavaScript ES5
> it can be used to replace ES5 Object.assign().
> etc.

There seems to be a mistake, _Object.assign_ is a new ES6 method (not ES5).

**Comment by rwieruch** [comment]
Oh damn, funny that it didn't caught any attention yet. Good find!

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/38f02bd45a8350edb355ec8e9a58962134d6218b
