### ISSUE TITLE
Explain JS filter function

### ISSUE THREAD

**Issue by brennenawana** [the-road-to-learn-react/the-road-to-learn-react#65]
Pasted below is our Slack discussion on this matter:

## Question
On page 35, when we define the function `isNotId(item)`, how do we have access to `item`? Looks like we get access from our map loop. Also, it’s interesting that we don’t have to call `isNotId` with parenthesis inside of our `updatedList`, because it is a function. Please explain.

## Response
Thanks for coming up with this! Indeed, it would be better to add more explanation to it.

The JavaScript built-in filter function (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) takes a function as input. The function has access to each value in the filtered list, because it iterates over the list. So it could be: `this.state.list.filter(function isNotId(item) {
return item.objectID !== id;
});` in the first step. But the book already applies the second step where the function gets extracted and only passed into .filter(isNotId).

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by rwieruch** [comment]
Thank you!

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/69b2a4696435d4114b80616ec17b9e8aa7cbc15b
