### ISSUE TITLE
enzyme adapter config needed

### ISSUE THREAD

**Issue by chri-roch12** [the-road-to-learn-react/the-road-to-learn-react#73]
I had to add additional configuration to the enzyme test unit. I was using React build 16, so had to use:
```
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```
To enable enzyme unit tests.

**Comment by rwieruch** [comment]
Oh thanks for this information! I will quickly try to add it to the book. Do you have any information if it is a temporary fix. Any links to issues are appreciated 👍

**Comment by kriswep** [comment]
It's right in their upgrading [docs](http://airbnb.io/enzyme/#upgrading-from-enzyme-2x-or-react--16) at the very top, so its gonna stay i suppose.

**Comment by chri-roch12** [comment]
Yeah, this looks like an additional step to keep in mind when installing the Enzyme utility. If you leave it out, when you run tests you will get an error message informing you that Enzyme does not have a specified Adapter config.

**Comment by rwieruch** [comment]
Solved in https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/cc378ed0dc457f339960e86736625975d55d7e74
