### ISSUE TITLE
“overwritten” methods

### ISSUE THREAD

**Issue by ghost** [the-road-to-learn-react/the-road-to-learn-react#74]
There are several occurrences of the phrase “methods overwritten” in the book. Shoud it be “methods overridden” instead?

**Comment by rwieruch** [comment]
Would it be more fitting compared to overwritten? I can change it, since I am writing on the 4th edition :)

**Comment by ghost** [comment]
It is more common to use term “overriding” and it would be more consistent with react docs as well.

**Comment by rwieruch** [comment]
Thank you! I will do it :)

**Comment by rwieruch** [comment]
Goes into next edition: https://github.com/rwieruch/the-road-to-learn-react/pull/72/commits/053479c43be2730a1baa3bcc1f5d8d18a066aabe
