### ISSUE TITLE
Cannot read property 'ReactCurrentOwner' of undefined

### ISSUE THREAD

**Issue by rwieruch** [the-road-to-learn-react/the-road-to-learn-react#83]
If you have started to read the ebook before the 4th edition was released, but grabbed the 4th edition recently (which uses React 16), you may see the following command line error message when executing your **Jest tests** for the first time:

```
FAIL  src/App.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'ReactCurrentOwner' of undefined

      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:621:36
      at Object.<anonymous> (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8254:3)
      at Object.<anonymous> (node_modules/react-test-renderer/index.js:6:20)
      at Object.<anonymous> (src/App.test.js:3:26)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.656s
```

You need to upgrade your project to React 16. Check your package.json if you run an old version of React. If you do so, type the following on the command line:

```
npm i -g npm-check-updates
npm-check-updates -u
npm install
```

It is a global npm module that can be used to update your dependencies, such as react or react-dom, in your package.json file. I should’ve mentioned it in the first place, for people grabbing the new edition who have an old React version installed.

See also https://github.com/the-road-to-learn-react/the-road-to-learn-react/issues/84

**Comment by rwieruch** [comment]
Note: Add in Change Log when node packages are upgraded when a new edition gets released.

**Comment by kafisher** [comment]
After upgrading to React 16 I get the following error after running npm test:

`TypeError: Cannot read property 'createEvent' of undefined`

I was able to fix it by reverting to the old version and explicitly setting 

`"devDependencies": { ... "react-test-renderer": "^15.5.4"}` 

in my package.json and running npm install again.

**Comment by rwieruch** [comment]
Closing this because React 16 was a long time ago and I don't expect people to run into this anymore.
