### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by CodeKommissar** [the-road-to-learn-react/the-road-to-learn-react#97]
Hi! I finished the book a couple of days ago and I really liked it. I just saw that there are some translations of the book (Chinese, Portuguese, etc) and I was wondering if I could do the same, but for a Spanish translation. How I would go about it?

**Comment by rwieruch** [comment]
Hey @CodeKommissar Thank you for your interest. A Spanish version is work in progress too. It's the only version which hasn't a GitHub repository yet :) Thank you again for your interest!
